language: php

dist: trusty

jdk:
    - openjdk8

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache

env:
    global:
        - DISPLAY=:99.0
        - CHROME_DRIVER_VERSION=2.36
        - SELENIUM_VERSION=3.6.0
    matrix:
        - DEPS="" PROFILE=default
#        - DEPS="--prefer-lowest" PROFILE=default
        - DEPS="" PROFILE=symfony2
#        - DEPS="--prefer-lowest" PROFILE=symfony2

php:
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

before_script:
    - Xvfb $DISPLAY -extension RANDR &> /dev/null &

    - wget "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
    - unzip chromedriver_linux64.zip
    - wget "https://selenium-release.storage.googleapis.com/${SELENIUM_VERSION%%.[[:digit:]]}/selenium-server-standalone-${SELENIUM_VERSION}.jar" -O selenium.jar
    - java -jar -Dwebdriver.chrome.driver=./chromedriver selenium.jar &> /dev/null &

    - echo "memory_limit = 2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

    - php -S localhost:8080 -t tests/fixtures/www tests/fixtures/www/router.php &> /dev/null &
    - cp behat.yml{.dist,}

    - COMPOSER_MEMORY_LIMIT=-1 composer update $DEPS

script:
    - ./bin/behat -fprogress --tags="~@user&&~@>php${TRAVIS_PHP_VERSION:0:3}" --no-interaction --profile=$PROFILE
